services:
  app:
    image: 1darkl1ght/testrepo_app:latest
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: test-app
    networks:
      - testrepo-network

  web:
    image: 1darkl1ght/testrepo_web:latest
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: test-web
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - testrepo-network

networks:
  testrepo-network: