apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | default "app-deployment" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.app.selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.app.selectorLabels | nindent 8 }}
    spec:
      containers:
      - name: test-app
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args: ["/app/build/testproj --logtostderr && sleep infinity"]